name: Flutter Build and Deploy

on:
  push:
    branches:
      - master
      - Develop
  pull_request:
    branches:
      - master
      - Develop

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
